app/urls.py
from django.conf.urls import url
from django.urls import path
from app import views 


#nome do app
app_name = "app"


#A relação entre as ações e os paths presentes nesta aplicação.
urlpatterns = [
	path('', views.index, name='index'),   #ação e path -> index, que é a página das medidas da embarcação
	path('mapa', views.mapa, name='mapa'), #ação e path -> mapa que é renderizado, auxiliando na geolocalização
	path('login/', views.user_login, name="user_login"), #ação e path -> login do usuário
	path('logout/', views.user_logout, name="user_logout"), #ação e path -> logout do usuário
	path('register/', views.register, name="user_register"), #ação e path -> registro de usuário
	path('adicionar_boias/', views.adicionar_boias, name="adicionar_boias"), #ação e path -> quando há a necessidade de adicionar boias
	path('boias/', views.get_boias, name="boias"), #ação e path -> retorna as boias adicionadas para compor o circuito de prova
	path('apagar_boias/', views.delete_boias, name="deletar_boias"), #ação e path -> quando a necessida de se apagar todas as boias
]

solaris/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

#caminhos raizes das aplicações deste escopo
#A aplicação de administração default, o admin/
# e a aplicação app, o software que irá renderizar as informações
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

templates/app/adicionar_boias.html
<!-- Carregando os arquivos estáticos. Estilo, imagens e scripts que a página necessita para funcionar--->
{% load staticfiles%}

<!DOCTYPE html>
<html>
  <head>
    
    <title>Solaris . Adicionar boias</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!--Font awesome-->
    <link href="{% static 'app/css/all.css'%}" rel="stylesheet" type="text/css" media="all" />  

    <!-- Latest compiled and minified CSS -->
    <link href="{% static 'app/css/bootstrap.css'%}" rel="stylesheet" type="text/css" media="all" />  
    <!--Estilização da página de adição de boias-->
    <link href="{% static 'app/css/adicionar_boias.css'%}" rel="stylesheet" type="text/css" media="all" />


    <!-- Latest compiled JavaScript -->
    <script src="{% static 'app/js/jquery.js'%}"></script>
    <script src="{% static 'app/js/bootstrap.js'%}"></script>

</head>

<body>

<!--Modal que contém o formulário para adição de boias-->
<div class="modal fade" id="adicionar_boias_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
      <!--Cabeçalho do modal-->
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Informe as coordenadas da boia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!--Formulário que adquire as localizações das boias-->
      <form method="POST" action="../adicionar_boias/">
        {% csrf_token %}

        <!--Corpo do modal-->
       <div class="modal-body">
          <!---Latitude-->
          <div class="form-group">
            <label for="latitude-boia" class="col-form-label">Latitude:</label>
             {{form_add_boia.latitude}}
          </div>
          <!---Longitude-->
          <div class="form-group">
            <label for="longitude" class="col-form-label">Longitude:</label>
            {{form_add_boia.longitude}}
          </div>
      </div>
        
      <div class="modal-footer">
        <!--Botão de fechar dialog-->
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        
        <!--Botão de inserir uma boia com base nas coordenadas inseridas no form do dialog-->
        <button type="submit" class="btn btn-primary">Adicionar</button>
      </div>
      </form>

    </div>
  </div>
</div>
<!--Fim do modal que contém o formulário de adição de boias-->


<div class="principal">

  <!--Cabeçalho--->
  <div class="header">

    <!---->
    <div>
      <h3>Solaris</h3> 
      <h6>Instituto Federal Fluminense</h6> 
    </div>

    <!--Ícone para sair da aplicação-->
    <div>
      <a href="{%url 'app:user_logout' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a>  
    </div>
  </div>

  <!--Área que mantém os botões de remover boias e o botão que abre o dialogo para inserir as boias-->
  <div class="main">   

    <!--Divs que exibem as coordenadas informadas pelo usuário--->
    <div class="area-cards-boias">
      <!--Se há boias inseridas--->
      {% if boias%}
        {% for b in boias%}
          <!--Adicionar elementos HTML para cada uma delas-->
          <div class="card-boia">
            <div class="card-boia-icone">
              <i class="fas fa-life-ring fa-2x"></i>
            </div>
            <!--Latitude e longitude de cada boia inserida-->
            <div class="card-boia-conteudo">
              <h5>Boia {{forloop.counter}}</h5>
              <label>Latitude: {{b.latitude}}</label> <br/>
              <label>Longitude: {{b.longitude}}</label>
            </div>
          </div>
        {%endfor%}
      {%else%}
        <h5>Nenhuma boia adicionada</h5>
      {%endif%}
    </div>
  </div>

      <!--Área dos botões que apagam todas as boias e o que abre o dialog que contém o formĺário para inserção das boias -->
    <div class="botoes-add-rmv-boias">    
        <!--Botão que remove todas as boias-->
        <button onclick="apagar_boias()" type="button" class="btn btn-primary">Remover boias</button>
        <!--Abre o dialog que contém o formulário que insere boias-->
        <button  type="button" class="btn btn-primary" data-toggle="modal" data-target="#adicionar_boias_form">Adicionar boia</button>
    </div>

  <!--Área que contém o botão que dereciona até à página de geolocalização da embarcação-->
  <div class="opcao">
    <div>
      <h5>Adicionar boias</h5>
    </div>

    <div>
      <img src="{%static 'app/img/logo-solaris.jpeg'%}" width="40" height="40">
    </div>

    <!--O botão que direciona até à página de geolocalização da embarcação-->
    <div>
       <a href="{%url 'app:mapa'%}" class="btn btn-primary btn-sm " role="button" aria-pressed="true">
          Ir para mapa
       </a>
    </div>
  </div>

</div>

<script type="text/javascript">
    //Função que apaga o vetor de boias presentes dentro do servidor
    function apagar_boias(){
      $.ajax({
        method: "get",
        url: '../apagar_boias',  //Contem o comando que limpa o vetor de boias
        success:function(responsedata){
          location.reload()
          alert("Todas as boias foram removidas.")
          
        } 
      })
    }
</script>

</body>  

</html>

templates/app/cadastro.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block conteudo %}

<head>
    <title>{%block title%}Solaris . Cadastro{%endblock%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link href="{% static 'app/css/cadastro.css'%}" rel="stylesheet" type="text/css" media="all" /> 
</head>

<body>
    <!-- main -->
    <div class="main-w3layouts wrapper">
        <div class="main-agileinfo">        
            <div class="agileits-top">
                <h1>Faça seu registro</h1>
                

                <form action="{% url 'app:user_register'%}" method="post">
                    {% csrf_token %}

                    <!--Campo-->
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-file-signature fa-1x"></i></span>
                        </div>

                        {{user_form.first_name}}
                                                
                    </div>

                    <!--Campo-->
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                          <span class="input-group-text"><i class="fas fa-user fa-1x"></i></span>
                        </div>
                        {{user_form.username}}             
                    </div>

                    <!--Campo-->
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                          <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{user_form.password1}}
                    </div>


                    <!--Campo-->
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        
                        {{user_form.password2}}
                        </div>

                    <!--Botão-->
                    <div class="d-flex justify-content-center mt-3 registro_container">
                        <input type="submit" value="Registrar" class="btn-block btn-lg registro_btn">
                    </div>
                    <!--Labels-->
                    <div class="mt-4">
                        <div id="conta-sn" class="d-flex justify-content-center">
                            Já possui uma conta?<a href="{% url 'app:user_login'%}" class="ml-2">Acesse aqui</a>
                        </div>
                    </div>

                    <div class="mt-2">
                        <div id="bs-copyright" class="d-flex justify-content-center">
                            &copy 2019 Bismarck Solaris
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
{%endblock%}

templates/app/index.html
{% load staticfiles%}

<!DOCTYPE html>
<html>
  <head>
    
    <title>{%block title%}Solaris . Aplicação{%endblock%}</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!--Font Awesome-->
    <link href="{% static 'app/css/all.css'%}" rel="stylesheet" type="text/css" media="all" />  

    <link href="{% static 'app/css/bootstrap.css'%}" rel="stylesheet" type="text/css" media="all" />  
    <link href="{% static 'app/css/index.css'%}" rel="stylesheet" type="text/css" media="all" />  
    

     <!-- Latest compiled JavaScript -->
     <script src="{% static 'app/js/jquery.js'%}"></script>
    <script src="{% static 'app/js/auxiliar_index.js'%}" ></script>

</head>

<body>

<div class="principal">

  <!--Cabeçalho--->
  <div class="header">
    <div>
      <h3>Solaris</h3> 
      <h6>Instituto Federal Fluminense</h6> 
    </div>

    <!-- Ícones para adicionar boias e sair da aplicação -->
    <div>

      {% if user.is_superuser %}
        <a href="{%url 'app:adicionar_boias' %}"><i class="fas fa-life-ring fa-2x"></i></a>
      {% endif %}


      <a href="{%url 'app:user_logout' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a>  
    </div>
  </div>

  <!--Área dos cards de medidas-->
  <div class="main">

    <!--Primeira informação-->
    <div class="card card-1">
      <div class="card-icon card-icon-1">
        B
      </div>

      <div class="card-info">
        <h6>Bateria principal</h6>
        <h3 id="bateria_principal">24.0 V</h3>
      </div>      
    </div> 

    <!--Segunda informação-->
    <div class="card card-2">
      <div class="card-icon card-icon-2">
        B
      </div>

      <div class="card-info">
        <h6>Baterias auxiliares</h6>
        <h3 id="baterias_auxiliares">12.0 V</h3>
      </div>
    </div>

    <!--Terceira informação-->
    <div class="card card-3">
      <div class="card-icon card-icon-3">
        P
      </div>
      
      <div class="card-info">
        <h6>Placas solares</h6>
        <h3 id="placas_solares">27.2 V</h3>
      </div>
    </div>

    <!--Quarta informação-->
    <div class="card card-4">
      <div class="card-icon card-icon-4">
        C
      </div>

      <div class="card-info">
        <h6>Corrente do motor</h6>
        <h3 id="corrente_motor">30.5 A</h3>
      </div>
    </div>


    <!--Quinta informação-->
    <div class="card card-5">
      <div class="card-icon card-icon-5">
        V
      </div>

      <div class="card-info">
          <h6>Velocidade do barco</h6>
          <h3 id="velocidade_barco">05.1 nós</h3>
      </div>     
    </div>
  
  </div> <!-- Fim da área que contém as informações de desempenho da embarcação-->

  <!--Área que contém o botão que dereciona até à página de geolocalização da embarcação-->
  <div class="opcao">
    <div>
      <h5>Medidas</h5>
    </div>

    <div>
      <img src="{%static 'app/img/logo-solaris.jpeg'%}" width="40" height="40">
    </div>

    <!--O botão que direciona até à página de geolocalização da embarcação-->
    <div>
       <a href="{%url 'app:mapa'%}" class="btn btn-primary btn-sm " role="button" aria-pressed="true">
          Ir para mapa
       </a>
    </div>

  </div>

</div>

</body>  

</html>

templates/app/login.html
<!--Carregar arquivos estáticos da página, como estilo, imagens e scripts-->
{% load staticfiles%}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Solaris . Login</title>

    <link href="{% static 'app/css/bootstrap.css'%}" rel="stylesheet" type="text/css" media="all" />  
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/login.css'%}">

    <!--FONTAWESOME - para os ícones-->
    <link href="{% static 'app/css/all.css'%}" rel="stylesheet" type="text/css" media="all" />  
    <!-- Latest compiled JavaScript -->
    <script src="{% static 'app/js/jquery.js'%}"></script>
    <script src="{% static 'app/js/bootstrap.js'%}"></script>

</head>

<body>

  <div class="painel-login">
    <div class="user-card">

        <!--Logo-->
        <div class="brand-logo-container">
          <img src="{% static 'app/img/logo-solaris.jpeg' %}" class="brand-logo" alt="Logo">
        </div>

        <div class="erros">
          {{ form_login.non_field_errors}} 
          {{form_login.usuario.errors}}
          {{form_login.senha.errors}}
        </div>
        
        <!--Formulário de identificação-->
        <div class="form-container">
          <form action="{% url 'app:user_login' %}" method="POST" novalidate>
            {% csrf_token %}
            <!--Campo de usuário-->
            <div class="user-input">
              <i class="fas fa-user"></i>
              {{form_login.usuario}}
            </div>

            <!--Campo de senha-->
             <div class="password-input">
              <i class="fas fa-key"></i>
              {{form_login.senha}}
            </div>

            <!--Botão-->
            <div class="botao">
                <button type="submit" class="login-btn">Login</button>  
            </div>
          </form>
          
          <h6>IFF - Instituto Federal Fluminense</h6> 
          <h6>2019</h6>
        </div>
    </div>
  </div>
</body>
</html>

templates/app/mapa.html
{% load staticfiles%}

<!DOCTYPE html>
<html>

<head>
  <title>{%block title%}Solaris . Aplicação{%endblock%}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


  <!--Font awesome-->
  <link href="{% static 'app/css/all.css'%}" rel="stylesheet" type="text/css" media="all" />  


  <!--Estilização da página de mapa-->
  <link href="{% static 'app/css/leaflet.css'%}" rel="stylesheet" type="text/css" media="all" />  
  <link href="{% static 'app/css/bootstrap.css'%}" rel="stylesheet" type="text/css" media="all" />  
  <link href="{% static 'app/css/mapa.css'%}" rel="stylesheet" type="text/css" media="all" />

  <!-- jQuery library -->
   <script src="{% static 'app/js/jquery.js'%}"></script>
  


</head>


<body>

<div class="principal">

  <!--Cabeçalho-->
  <div class="header">
    <div>
      <h3>Solaris</h3> 
      <h6>Instituto Federal Fluminense</h6>
    </div>

    <!--Ícones-->  
    <div>

       {% if user.is_superuser %}
          <a href="{%url 'app:adicionar_boias' %}"><i class="fas fa-life-ring fa-2x"></i></a>
      {% endif %}

      <a href="{%url 'app:user_logout' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a>  
    </div>

  </div>

  <!--Área de renderização do mapa-->
  <div class="main">
    <!--Div responsável por "guardar o conteúdo do mapa"-->
    <div id="mapa">
    </div>

  </div>

  <!--Área que contém o botão que direciona até a página das informações da embarcação-->
  <div class="opcao">
    <div>
      <h5>Localização</h5>
    </div>

    <div>
        <img src="{%static 'app/img/logo-solaris.jpeg'%}" width="40" height="40">
    </div>

    <!--O botão que direciona até a página das informações da embarcação-->
    <div>
      <a href="{% url 'app:index' %}" class="btn btn-primary btn-sm " role="button" aria-pressed="true">Ir para medidas</a>
    </div>

  </div>
  
</div>

</body> 

  <!--Script da bilbioteca de mapa-->  
  <script src="{% static 'app/js/leaflet.js'%}"></script>

  <!--Conjunto de funções implementadas para renderização do mapa-->
  <script type="text/javascript" src="{% static 'app/js/controle_mapa/controle_mapa.js'%}"></script>
  <!--Main-->
  <script type="text/javascript" src="{% static 'app/js/auxiliar_mapa.js'%}"></script> 

</html>